### PR TITLE
updated the notification to be persistent and have a high priority

### PR DESCRIPTION
**Pull request by BenjaminWegener**
to deal with force close on devices with low ram, helped on my old redmi 4x with a game, that killed smartautoclicker.

### CODE REVIEW

**Comment by BenjaminWegener** [comment]
would be beneficial

**Comment by millertrial1** [comment]
How do I implement this change exactly ? I think I have been experiencing the same issue with low RAM phones using auto clicker app on them. 

> to deal with force close on devices with low ram, helped on my old redmi 4x with a game, that killed smartautoclicker.

**Comment by millertrial1** [comment]
This is my first time using Github and I'm not really familiar with all of this. I downloaded the master zip and and downloaded android studio and made the change or at least I think I did, but I was having trouble building the apk properly or saving those changes properly I think, i have never used that before and was not really sure what I was doing.

I have a question, would it be possible for you to provide me with a smart auto clicker apk with these changes already made ? I would appreciate that very much. I really want to test this.

> @millertrial1 clone the master and change that line in smartautoclicker/src/main/java/com/buzbuz/smartautoclicker/SmartAutoClickerService.kt

**Comment by Nain57** [comment]
Sorry about my late answer, for a reason I don't understand, the PR mails are going to my spam folder -_-'

In the [last release](https://github.com/Nain57/Smart-AutoClicker/releases/tag/1.5.2), I have made some changes that improve the application stability.

Alongside with that, I have made some changes on the notification:
* set the notification as Ongoing: this is part of a Android 13 change, required to keep to notification alive as the user can now dismiss a foreground service notification. Also with a few investigation, it seems like it can help keeping the service alive on some problematic phone brands (despite the fact that it should not, as it is not the case in AOSP implementation and documentation).

* set the category to SERVICE: this should be set automatically by the Android Framework, but once again, problematic phone brands have changed that...

* set the notification as LocalOnly: to avoid displaying the notification on a Smart Watch

 
For the other values proposed in this PR:
* setPriority: this is the same as the importance in the notification channel for Android < 8.0. NotificationCompat is taking care of setting the correct value for the correct Android version.
* NotificationChannel importance: according to the [Android API](https://developer.android.com/reference/android/app/NotificationChannel?hl=en#NotificationChannel(java.lang.String,%20java.lang.CharSequence,%20int)) (and cross-checked by my self in the[ source code](https://cs.android.com)), it only impacts the way of displaying the notification to the user. I have checked a lot of resources and none of them report a lifecycle change on a foreground service by changing this parameter.


Once again, I highly recomand checking [dontkillmyapp ](https://dontkillmyapp.com) and apply all tips for your phone if they are problematic.

**Comment by millertrial1** [comment]
> 

I have installed the latest version of Smart Auto on all my phones, the problem is still occurring for me on all phones. Also I have already taken every possible option to enhance the power related things in dontkillmyapp topic. 

But what I have noticed is that it seems the more events I have in a scenario increases the chances that the scenario is killed at random. I have never had problems with a scenario that has like maybe 10 events of less for example, I can run that scenario all day every day. But once it gets to a bigger number of events it ALWAYS dies eventually. It seems the better the phone maybe the longer it lasts but it always dies and fairly quick. I don't know if that information helps in anyway to figure out what is going on.

**Pull request closed without merging**
